# Tasks specific for this project
---

- name: ensure required paths exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - "{{ config['path.data'] }}"
    - "{{ config['path.logs'] }}"

- name: copy Java options
  become: yes
  template:
    src: jvm.options
    dest: "{{ conf_dir }}/jvm.options"
  notify: restart {{ project }}
