---

- name: reload systemd configuration
  command: systemctl daemon-reload

- name: restart {{ project }}
  service: name={{ service_name }} state=restarted enabled=yes
  when:
    - restart_on_change
